language: python

python:
  - 2.7

sudo: false

install:
  - make setup

before_script:
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"

script:
  - make test
